#!/usr/bin/env node
// Interactive first-run configuration wizard. Writes .env next to the project
// root, then the server boots with the generated configuration.
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { v4 as uuidv4 } from "uuid";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENV_FILE = path.join(ROOT_DIR, ".env");
const FORCE = process.argv.includes("--force");

const SAFE_EXECUTABLES_DEFAULT =
  "pwd,ls,find,cat,head,tail,wc,du,df,ps,whoami,hostname,git,git.exe,node,node.exe,npm,npm.cmd,npx,npx.cmd,python,python.exe,python3,python3.exe,rg,rg.exe,sed,where,where.exe,ipconfig,tasklist";

function parseEnvFile(filePath) {
  const values = {};
  if (!existsSync(filePath)) return values;
  for (const line of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*)\s*$/);
    if (match && !line.trim().startsWith("#")) values[match[1]] = match[2].trim();
  }
  return values;
}

const existing = parseEnvFile(ENV_FILE);

if (existsSync(ENV_FILE) && !FORCE) {
  console.log("已检测到 .env,跳过配置向导。需要重新配置请运行 npm run setup。");
  process.exit(0);
}

const rl = createInterface({ input: stdin, output: stdout });

let inputClosed = false;
const closedPromise = new Promise((resolve) => rl.once("close", resolve));

async function askRaw(prompt) {
  if (inputClosed) return "";
  try {
    return await Promise.race([rl.question(prompt), closedPromise.then(() => "")]);
  } catch {
    return "";
  }
}

async function ask(question, fallback = "") {
  const suffix = fallback ? ` (回车 = ${fallback})` : "";
  const answer = (await askRaw(`${question}${suffix}: `)).trim();
  return answer || fallback;
}

async function askBoolean(question, fallbackYes) {
  const hint = fallbackYes ? "Y/n" : "y/N";
  for (;;) {
    const answer = (await askRaw(`${question} (${hint}): `)).trim().toLowerCase();
    if (inputClosed) return fallbackYes;
    if (!answer) return fallbackYes;
    if (["y", "yes", "1"].includes(answer)) return true;
    if (["n", "no", "0"].includes(answer)) return false;
    console.log("请输入 y 或 n。");
  }
}

console.log("");
console.log("=== ChatGPT Local Control MCP 配置向导 ===");
console.log("");

const previousAllowAll =
  existing.ALLOW_WRITES === "1" &&
  existing.ALLOW_SHELL === "1" &&
  existing.ALLOW_SCREENSHOT === "1" &&
  existing.ALLOW_OPEN === "1" &&
  existing.ALLOW_GUI === "1";

const roots = await ask("允许 ChatGPT 访问的目录(Windows 多目录用分号分隔)", existing.LOCAL_CONTROL_ROOTS || os.homedir());

const allowAll = await askBoolean("开启全部高权限能力(写文件/命令/截屏/打开目标/GUI 键鼠)?", previousAllowAll || Object.keys(existing).length === 0);
let allowWrites = allowAll;
let allowShell = allowAll;
let allowUnsafeShell = allowAll;
let allowScreenshot = allowAll;
let allowOpen = allowAll;
let allowGui = allowAll;

if (!allowAll) {
  allowWrites = await askBoolean("允许写文件 (ALLOW_WRITES)?", existing.ALLOW_WRITES === "1");
  allowShell = await askBoolean("允许运行命令 (ALLOW_SHELL)?", existing.ALLOW_SHELL === "1");
  allowUnsafeShell = allowShell && (await askBoolean("允许任意命令与 PowerShell 脚本 (ALLOW_UNSAFE_SHELL)?", existing.ALLOW_UNSAFE_SHELL === "1"));
  allowScreenshot = await askBoolean("允许截屏 (ALLOW_SCREENSHOT)?", existing.ALLOW_SCREENSHOT === "1");
  allowOpen = await askBoolean("允许打开 URL/文件/应用 (ALLOW_OPEN)?", existing.ALLOW_OPEN === "1");
  allowGui = await askBoolean("允许鼠标键盘控制 (ALLOW_GUI)?", existing.ALLOW_GUI === "1");
}

const publicUrl = await ask("对外 HTTPS 地址 PUBLIC_MCP_URL(可留空,留空则启动时提示配置隧道)", existing.PUBLIC_MCP_URL || "");

let secretKey = await ask("SECRET_KEY 密钥(回车 = 自动生成 UUID)", existing.SECRET_KEY || "");
if (!secretKey) secretKey = uuidv4();

let controlPin = await ask("LOCAL_CONTROL_PIN 备用 PIN(回车 = 自动生成 UUID)", existing.LOCAL_CONTROL_PIN || "");
if (!controlPin || controlPin === "change-me-to-a-long-random-secret") controlPin = uuidv4();

rl.close();

if (existsSync(ENV_FILE)) {
  const backup = `${ENV_FILE}.backup`;
  renameSync(ENV_FILE, backup);
  console.log(`原 .env 已备份为 ${path.basename(backup)}`);
}

const envContent = `# Generated by scripts/setup-wizard.js
# MCP HTTP endpoint
PORT=8787
MCP_PATH=/mcp

# File tools are restricted to these roots. Separate multiple paths with the
# platform path delimiter: ":" on macOS/Linux, ";" on Windows.
LOCAL_CONTROL_ROOTS=${roots}

# Fallback PIN for privileged tools. Not needed when the connector URL carries
# a valid secret key.
LOCAL_CONTROL_PIN=${controlPin}

OAUTH_TOKEN_TTL_SECONDS=86400
OAUTH_REQUIRE_APPROVAL_PIN=0

ALLOW_WRITES=${allowWrites ? 1 : 0}
ALLOW_SHELL=${allowShell ? 1 : 0}
ALLOW_UNSAFE_SHELL=${allowUnsafeShell ? 1 : 0}
ALLOW_SCREENSHOT=${allowScreenshot ? 1 : 0}
ALLOW_OPEN=${allowOpen ? 1 : 0}
ALLOW_GUI=${allowGui ? 1 : 0}
ALLOW_APPLESCRIPT=${existing.ALLOW_APPLESCRIPT ?? 0}

SAFE_EXECUTABLES=${existing.SAFE_EXECUTABLES || SAFE_EXECUTABLES_DEFAULT}

# Output and file safety limits.
MAX_COMMAND_OUTPUT_CHARS=20000
MAX_READ_BYTES=262144
MAX_DIRECTORY_ENTRIES=300
COMMAND_TIMEOUT_MS=15000

# Public HTTPS URL shown at startup for ChatGPT connector setup.
PUBLIC_MCP_URL=${publicUrl}

# Secret key that grants full control via ?secret-key= or the x-secret-key header.
SECRET_KEY=${secretKey}
`;

writeFileSync(ENV_FILE, envContent, "utf8");

console.log("");
console.log(`.env 已生成: ${ENV_FILE}`);
console.log(`允许目录: ${roots}`);
console.log(`高权限能力: writes=${allowWrites ? 1 : 0} shell=${allowShell ? 1 : 0} unsafeShell=${allowUnsafeShell ? 1 : 0} screenshot=${allowScreenshot ? 1 : 0} open=${allowOpen ? 1 : 0} gui=${allowGui ? 1 : 0}`);
if (publicUrl) {
  console.log(`ChatGPT connector URL: ${publicUrl}?secret-key=${secretKey}`);
}
console.log(`SECRET_KEY: ${secretKey}`);
console.log("");
console.log("正在启动服务...");
